### ISSUE TITLE
Database: changes to hydrant_inspections table 

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Hydrants#1]
Environment: vm-1108s08
Make the following changes to the hydrant_inspections table
1.  Rename to HYDRANT_STATUS
2.  Rename WORK_REQ to CSR_SR_NUM
3.  Add CW_SR_NUM
4.  Remove LOCATION_DESC  
5.  Remove CUSTODIAL_LOCK_TYPE
6.  Remove SURFACE_COVER_TYPE
7.    Add INSP_TYPE
8.    Add BROKEN_FLANGE_YN
Add flow test fields to HYDRANT_STATUS
1.  FLOW_STATIC_PSI
2.  FLOW_RESID_PSI
3.  FLOW_AT_20PSI

**Comment by rssidlowski** [comment]
![hyd_insp_fields1](https://cloud.githubusercontent.com/assets/5039052/6150690/cbfcb0ce-b1de-11e4-9b06-7b95e5ccf054.PNG)

**Comment by gerrykelly** [comment]
this was done
