### ISSUE TITLE
Add role to restrict update hydrant status to IN SERVICE, OUT OF SERVICE to only allow Baltimore City Fire Dept

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Hydrants#16]
Within the City of Baltimore, only the members of the Fire Department should be allowed to update the hydrant status to 
- In service
- Out of service
  Other users of the Hydrant mobile application should be allowed to update the status to 
- In service repairs needed
- In service pending unit inspection

**Comment by rssidlowski** [comment]
only fd can change status to in service.
any users can change to any other status.

**Comment by jday3** [comment]
Done

**Comment by rssidlowski** [comment]
Does this key off the person logged in and their role or does it use the inspector organization? Can you default the inspector and inspector org to the current person logged in?

**Comment by alanfoster99** [comment]
just to make sure I am reading this correctly, all users are allowed to set it as "Out of Service" correct?

**Comment by rssidlowski** [comment]
Correct.

**Comment by jday3** [comment]
It is checking the role of the logged in user from the Administration application. I could pull the inspector name from the logged in user, but we would have to be sure that that user is in the Hydrants database

**Comment by rssidlowski** [comment]
Verified.
