### ISSUE TITLE
Add layer of hydrants not inspected within last 6 months

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Hydrants#17]
Add a new feature layer of hydrants not inspected within the last 6 months and allow the user to turn on and off in the application.

**Comment by JMurk** [comment]
I've published a new service called Hydrants_Needing_Inspection on dev.  Gerry can code the new service into the TOC.

Check the symbology out and let me know what you think.

**Comment by rssidlowski** [comment]
Can you incorporate this?

**Comment by jday3** [comment]
Its there now in dev. Off by default.

**Comment by rssidlowski** [comment]
Verified.
