### ISSUE TITLE
Report: number of inspections completed over date range

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Hydrants#18]
Create a new report of the number of inspections completed over the user entered date range and the resulting status.  The report would look as follows:
![image](https://cloud.githubusercontent.com/assets/5039052/6944988/a414547a-d864-11e4-9846-216a9c1543f5.png)

**Comment by jday3** [comment]
Do we not want to show the other existing statuses? (Unknown, New Hydrant, Marked for removal). Also if we dont want to show those, should the total count only include hydrants with the statuses on the report?

**Comment by rssidlowski** [comment]
for now go ahead and list them all.  I will clarify.

**Comment by jday3** [comment]
Done

**Comment by rssidlowski** [comment]
Where is this report?  I don't see it in the dropdown list of reports.
![reportlist](https://cloud.githubusercontent.com/assets/5039052/7107046/ac24e44a-e124-11e4-82c8-7ad59b33cfbd.PNG)

**Comment by jday3** [comment]
It is under inspections summary

**Comment by rssidlowski** [comment]
That will work.
