### ISSUE TITLE
Report: hydrant inspection detail 

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Hydrants#19]
Allow user to select a hydrant id and then select which inspection from the resulting dates of inspections or display all.  The resulting report should look similar to below:
![image](https://cloud.githubusercontent.com/assets/5039052/6945543/7c777f38-d868-11e4-904a-15cea55b8379.png)

If user selects all inspections, show the most recent inspection for the selected hydrant and then display the rest of the inspections in reverse chronological date order as shown below.

![image](https://cloud.githubusercontent.com/assets/5039052/6945968/352b87e8-d86b-11e4-938d-0b5acd6d2fc2.png)

**Comment by jday3** [comment]
Done

**Comment by rssidlowski** [comment]
Report is getting truncated when export to pdf:
![hyinspreporttrunc](https://cloud.githubusercontent.com/assets/5039052/7107033/3023bda8-e124-11e4-9b61-b961d5d31a0a.PNG)

**Comment by rssidlowski** [comment]
For the following fields, display the lookup value instead of the code in the report:
Inspector
Inspector Organization
Status

**Comment by jday3** [comment]
Done

**Comment by rssidlowski** [comment]
I added new inspections and now the first inspection doesn't show up in the report. 
![hydhistory](https://cloud.githubusercontent.com/assets/5039052/7116188/a6fcb972-e1bd-11e4-816c-82166a1f32b1.PNG)
![hydinspreport](https://cloud.githubusercontent.com/assets/5039052/7116191/a9d73352-e1bd-11e4-9611-908f1f8a85e4.PNG)

**Comment by jday3** [comment]
Fixed

**Comment by rssidlowski** [comment]
Verified.
