### ISSUE TITLE
Report: Summary of Hydrant Inspections by Inspecting Organization and Date Range

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Hydrants#20]
Allow the user to select a date range and displays the resulting list of Hydrant Inspections conducted by each organizations.
For example if user selects 3/4/2015, allow them to select an inspecting organization from a drop down list or all and the result should look like the following:
![image](https://cloud.githubusercontent.com/assets/5039052/6947804/ad453a38-d877-11e4-9060-f21e400b9484.png)

**Comment by jday3** [comment]
Done

**Comment by rssidlowski** [comment]
Make the report landscape so that all the data fits on one page. Also add a total for the total number of hydrants in the last column.

**Comment by rssidlowski** [comment]
The selection of the organization is grayed out. 
![inspreport](https://cloud.githubusercontent.com/assets/5039052/7107010/25e5cddc-e123-11e4-9cec-f008bd565148.PNG)

**Comment by rssidlowski** [comment]
Created an inspection today (4/13) ran the report with the following date range:
3/1/2015 - 4/13/2015 and there were no inspections in the report.
![reportinspsumm](https://cloud.githubusercontent.com/assets/5039052/7114619/4b33c618-e1ad-11e4-9c3e-af01754c6907.PNG)
![reportinspsummempty](https://cloud.githubusercontent.com/assets/5039052/7114643/5e3fe822-e1ad-11e4-8fc9-be2574b718a1.PNG)
Here is the saved inspection:
![inspsaved](https://cloud.githubusercontent.com/assets/5039052/7114656/81e3206e-e1ad-11e4-83c3-819596508456.PNG)

**Comment by jday3** [comment]
Done

**Comment by rssidlowski** [comment]
Can you make the pdf fit on one page?
![pdfreport](https://cloud.githubusercontent.com/assets/5039052/7122735/5689b566-e1eb-11e4-8cdf-e3c5ce7dbac2.PNG)

**Comment by jday3** [comment]
fixed

**Comment by rssidlowski** [comment]
Verified.
