### ISSUE TITLE
Create new Hydrants icon for mobile dashboard

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Hydrants#22]
To be coordinated with Tiffany.

**Comment by rssidlowski** [comment]
![hydranticon](https://cloud.githubusercontent.com/assets/5039052/7072209/8c262b40-deb8-11e4-8200-1a2462ae2282.png)

**Comment by rssidlowski** [comment]
Add to the mobile portal.  Actual file sent in email.

**Comment by jday3** [comment]
Done (dev)

**Comment by rssidlowski** [comment]
Verified.
