### ISSUE TITLE
Update to latest orthos

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Hydrants#23]
Have orthos from 200 and 1997, update to latest after Ian builds mosaic.
![orthos](https://cloud.githubusercontent.com/assets/5039052/7046585/e5480f5c-ddd4-11e4-8397-be465db0bfc5.PNG)

**Comment by alanfoster99** [comment]
There is a mosaic here of the 2014s:

\dpw-gd01-srv\Geodata\orthos\2014\ECW

Is this what you want?

**Comment by JMurk** [comment]
I've tried what Alan provided and just can't seem to get it to show once the service is published.  Ian is working on a 2014 mosaic and placing in SDE.  I will put it in when he gets that finished.

**Comment by alanfoster99** [comment]
There may be an issue w Arcgis server and ecw format. Not sure they have the licensing to serve it.

Alan E. Foster
City of Baltimore
Business Analyst and Lead, Data Management Section – Office of Asset Management
1.410.316.0812tel:1.410.316.0812
1.410.396.tel:1.410.396.00220022tel:1.410.396.0022

alan.foster@kci.commailto:alan.foster@kci.com
alan.foster@baltimorecity.govmailto:alan.foster@baltimorecity.gov

[cid:image001.jpg@01D0615E.BF5679C0]http://kci.com/

On Apr 8, 2015, at 19:52, Joe Murk <notifications@github.com<mailto:notifications@github.com>> wrote:

I've tried what Alan provided and just can't seem to get it to show once the service is published. Ian is working on a 2014 mosaic and placing in SDE. I will put it in when he gets that finished.

**Comment by rssidlowski** [comment]
Orthos installed on PST (2011),  duplicate this here.  See https://github.com/rssidlowski/Pollution_Source_Tracking/issues/139.

**Comment by jday3** [comment]
Since it was added to the aerial map service it automatically carried over into hydrants (and other mobile apps that use the aerial imagery map service)

**Comment by rssidlowski** [comment]
Verified.

**Comment by JMurk** [comment]
FYI, 2014 Orthos have been added to all applications.
