### ISSUE TITLE
Settings: unable to toggle layers

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Hydrants#24]
In COBDEV: http://dpwdev.baltimorecity.gov/water/hydrants/index.aspx using google chrome.
Unable to toggle layers on the settings page.
When the toggle is on it should be green and to the right.  
Unable to turn toggle on for the different layers.
![toggle](https://cloud.githubusercontent.com/assets/5039052/8546945/6f648030-2489-11e5-9efb-f9c114319241.PNG)

**Comment by gerrykelly** [comment]
fixed (I did not edit the source code, since I don't think I have the most recent version, so I can't get rid of the fireman)

**Comment by rssidlowski** [comment]
I just tried in Chrome and still not working.

**Comment by rssidlowski** [comment]
This is working now.
