### ISSUE TITLE
Add Plat layer to Hydrants

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Hydrants#26]
Add a Plat layer to the Hydrants and allow the user to turn on and off in the settings.

**Comment by alanfoster99** [comment]
This is the plat footprints w/ layer names, right, and not the water plat rasters?

**Comment by JMurk** [comment]
I would assume they would want both.

**Comment by alanfoster99** [comment]
Amy is trying to get Wachs away from using the plats -- Sewelo discussed that they assign work by plat boundary, so that's why I'm thinking just the bounds.   Will let Regina decide!

**Comment by JMurk** [comment]
I created a new map service on City dev called "Water_Plat_Index".  If we need to add the actual image layer, we can.

**Comment by gerrykelly** [comment]
Done

**Comment by rssidlowski** [comment]
Verified in cobdev.
