### ISSUE TITLE
Discrepancy: add ability to add discrepancy

### ISSUE THREAD

**Issue by rssidlowski** [rssidlowski/Hydrants#5]
This is the same as we have in PST.  Add a button to add a discrepancy. 
![discrepancy](https://cloud.githubusercontent.com/assets/5039052/6150866/d681209c-b1df-11e4-9149-29f53104f0a2.PNG)

**Comment by jday3** [comment]
This appears to already be in there

**Comment by rssidlowski** [comment]
Tried to add a new discrepancy and it just seems to clock: 
![addnewdisc](https://cloud.githubusercontent.com/assets/5039052/7120308/48d0e7ac-e1da-11e4-94df-05643b12f773.PNG)

**Comment by rssidlowski** [comment]
Add the discrepancy layer to the Hydrants settings page.

**Comment by jday3** [comment]
Done and fixed.

**Comment by rssidlowski** [comment]
Verified.
